plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 13
  sourceType: module

rules: {
    no-console: 0,
    import/extensions: 0,
    no-useless-escape: 0,
}
